### ISSUE TITLE
Issues with Go:path, APP_DOMAIN, ContainerCrash & LDAP

### ISSUE THREAD

**Issue by AJOCHAM** [StevenWeathers/thunderdome-planning-poker#127]
I started the Thunderdome container via docker-compose on an Ubuntu machine.
Each time I "leave a game" the container crashes (see log below)

I also could not figure out how to solve these issues:
- exec: "go": executable file not found in $PATH:
- WebUI via 127.0.0.1:8080, even when I adapt this in a docker-compose.overwrite.yml, it does not change:

`version: '3.1'

services:
  thunderdome:
    environment:
      - APP_DOMAIN=myservername.myDomain.com`

```

thunderdome_1  | 2020/11/05 13:26:23 Access the WebUI via 127.0.0.1:8080
thunderdome_1  | 2020/11/05 13:26:29 error: websocket: close 1000 (normal)
thunderdome_1  | panic: concurrent write to websocket connection
thunderdome_1  |
thunderdome_1  | goroutine 34 [running]:
thunderdome_1  | github.com/gorilla/websocket.(*messageWriter).flushFrame(0xc0001b2e40, 0x140cd01, 0x140cda8, 0x0, 0x0, 0x0, 0x44bb18)
thunderdome_1  | 	/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:610 +0x612
thunderdome_1  | github.com/gorilla/websocket.(*Conn).WriteMessage(0xc000020160, 0x8, 0x140cda8, 0x0, 0x0, 0x6b4426a21, 0x13efd00)
thunderdome_1  | 	/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:763 +0x23d
thunderdome_1  | main.(*connection).write(0xc0002b2ad0, 0x8, 0x140cda8, 0x0, 0x0, 0x0, 0x0)
thunderdome_1  | 	/go/src/github.com/stevenweathers/thunderdome-planning-poker/client.go:266 +0xa9
thunderdome_1  | main.(*subscription).writePump(0xc0003b43c0)
thunderdome_1  | 	/go/src/github.com/stevenweathers/thunderdome-planning-poker/client.go:281 +0x1f8
thunderdome_1  | created by main.(*server).serveWs.func1
thunderdome_1  | 	/go/src/github.com/stevenweathers/thunderdome-planning-poker/client.go:350 +0x9f1
thunderdome_1  | 2020/11/05 13:26:56 exec: "go": executable file not found in $PATH:
```

**Comment by StevenWeathers** [comment]
Think you accidentally opened this twice, closing duplicate.
