### ISSUE TITLE
Error on first LDAP Login

### ISSUE THREAD

**Issue by jzaeske** [StevenWeathers/thunderdome-planning-poker#145]
I've configured a thunderdome instance with authentication mode to ldap.

If a new user tries to authenticate, the first atempt fails and the log shows following error:

```
2021/01/14 11:01:15 sql: no rows in result set
2021/01/14 11:01:15 Warrior [email] does not exist in database, auto-recruit
2021/01/14 11:01:15 http: panic serving 172.24.0.15:50186: runtime error: invalid memory address or nil pointer dereference
goroutine 244 [running]:
net/http.(*conn).serve.func1(0xc0005e6000)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0xb28fc0, 0x13e82f0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
main.(*server).handleLdapLogin.func1(0xf1a800, 0xc00051a8c0, 0xc00057b500)
	/Users/stevenweathers/Documents/GitHub/thunderdome-planning-poker/handlers.go:359 +0x1f7
net/http.HandlerFunc.ServeHTTP(0xc00022c500, 0xf1a800, 0xc00051a8c0, 0xc00057b500)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000106180, 0xf1a800, 0xc00051a8c0, 0xc00057b300)
	/Users/stevenweathers/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
net/http.serverHandler.ServeHTTP(0xc000342000, 0xf1a800, 0xc00051a8c0, 0xc00057b300)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0005e6000, 0xf1cc00, 0xc00007d9c0)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
```

The second atempt to login is successful and a new user is shown in the administration interface.

**Comment by StevenWeathers** [comment]
Fixed by PR#146
