### ISSUE TITLE
LDAP authentication stopped working after upgrading from 2.12.2 to 2.13.0

### ISSUE THREAD

**Issue by felipecrs** [StevenWeathers/thunderdome-planning-poker#326]
The browser logs says:

```log
api/auth/ldap:1 Failed to load resource: the server responded with a status of 502 ()
```

The container logs says:

```log
2022/06/28 15:53:04 http: panic serving 192.168.186.196:45726: runtime error: invalid memory address or nil pointer dereference
goroutine 80 [running]:
net/http.(*conn).serve.func1()
/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/server.go:1802 +0xb9
panic({0xae8700, 0x267bca0})
/opt/hostedtoolcache/go/1.17.11/x64/src/runtime/panic.go:1047 +0x266
github.com/StevenWeathers/thunderdome-planning-poker/api.(*api).authAndCreateUserLdap(0xc0008d8c30, {0xc0009dc340, 0x1e}, {0xc000a98190, 0xa})
/home/runner/work/thunderdome-planning-poker/thunderdome-planning-poker/api/util.go:361 +0xd33
github.com/StevenWeathers/thunderdome-planning-poker/api.(*api).handleLdapLogin.func1({0xfd2b18, 0xc0002aa000}, 0xc0017fa120)
/home/runner/work/thunderdome-planning-poker/thunderdome-planning-poker/api/auth.go:59 +0xf7
net/http.HandlerFunc.ServeHTTP(0xc000200100, {0xfd2b18, 0xc0002aa000}, 0x2695420)
/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/server.go:2047 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001da540, {0xfd2b18, 0xc0002aa000}, 0xc000200000)
/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xfd0d60}, {0xfd2b18, 0xc0002aa000}, 0xc000200000)
/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0017e23c0, {0xfd7aa0, 0xc00189e720})
/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
/opt/hostedtoolcache/go/1.17.11/x64/src/net/http/server.go:3034 +0x4e8
```

Version 2.16.1 still has the same problem.

**Comment by StevenWeathers** [comment]
Version 2.16.2 has the fix for this, let me know if you have any further issues.
